name: "Generate Changeset"

# Triggered when a PR is merged
on:
  pull_request:
    types: [closed]

jobs:
  generate-changeset:
    # Only run if PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    name: Generate Changeset
    runs-on: ubuntu-latest

    permissions:
      contents: write # Grant write access to the repository contents

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      # Scan for @since tags
      - name: Scan for @since Tags
        id: since_tags
        run: |
          TAGS=$(node -e "
            const { generateSinceTagsMetadata } = require('./scripts/scan-since-tags');
            generateSinceTagsMetadata().then(result => {
              console.log(JSON.stringify(result));
            });
          ")
          echo "::set-output name=tags::$TAGS"

      # Generate changeset
      - name: Generate Changeset
        id: generate
        run: |
          echo "PR_TITLE=${{ env.PR_TITLE || github.event.pull_request.title || 'feat: No title' }}" >> $GITHUB_ENV
          echo "PR_BODY=${{ env.PR_BODY || github.event.pull_request.body || 'No body' }}" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ env.PR_NUMBER || github.event.pull_request.number || 'No number' }}" >> $GITHUB_ENV
          # Run with error handling
          if ! node scripts/generate-changeset.js; then
            echo "Error generating changeset"
            exit 1
          fi

      # Create PR with changeset
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7

        with:
          token: ${{ secrets.SYNC_TOKEN }}
          commit-message: "chore: add changeset for PR #${{ github.event.pull_request.number }}"
          branch: changeset-pr-${{ github.event.pull_request.number }}
          title: "chore: add changeset for PR #${{ github.event.pull_request.number }}"
          base: "develop"
          body: |
            This PR was automatically created to add a changeset for PR #${{ github.event.pull_request.number }}.

            The changeset will be used to:
            1. Update the changelog
            2. Determine version bump
            3. Update version numbers
            4. Update @since tags

            ### Validation
            - [ ] Changeset format is correct
            - [ ] Version bump type is appropriate
            - [ ] Breaking changes are properly documented
            - [ ] Upgrade instructions are included (if needed)
            - [ ] @since tags are identified for update

            ### Files with @since Tags to Update
            ${{ steps.since_tags.outputs.tags != '' && fromJson(steps.since_tags.outputs.tags).sinceFiles || 'No files with @since tags found.' }}

            Total tags to update: ${{ steps.since_tags.outputs.tags != '' && fromJson(steps.since_tags.outputs.tags).totalTags || 0 }}
          labels: |
            automated pr
            changeset
