name: Test Scripts

on:
  push:
    branches:
      - develop
      - master
      - "1.x/master"
      - next-major
  pull_request:
    branches:
      - develop
      - master
      - "1.x/master"
      - next-major
    paths:
      - 'scripts/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/test-scripts.yml'

jobs:
  test:
    name: Node ${{ matrix.node }} Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 21]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test:changesets

      # Optional: Add coverage reporting
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: scripts
          fail_ci_if_error: true